### ISSUE TITLE
Error when creating timescaledb_toolkit extension using the source

### ISSUE THREAD

**Issue by ebreijo** [timescale/timescaledb-toolkit#188]
**Relevant system information:**
 - OS: Ubuntu 18.04.1 LTS
 - PostgreSQL version (output of `SELECT version();`): PostgreSQL 13.2 (Ubuntu 13.2-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
 - TimescaleDB Toolkit version (output of `\dx timescaledb_toolkit` in `psql`): 1.0.0
 - Installation method: source

**Describe the bug**

I’m trying to install the timescaledb toolkit on our timescale 2.3.1 database. I’ve followed the steps documented in this github: https://github.com/timescale/timescaledb-toolkit

After successfully running all those steps, the extension is installed under `/usr/share/postgresql/13/extension`.
But when executing `CREATE EXTENSION IF NOT EXISTS timescaledb_toolkit CASCADE;` I get the following error: 
“ERROR:  aggregate cannot accept shell type tdigest”

Is there something I’m missing? How do I get the extension to work on the database?

**Comment by ebreijo** [comment]
Closing this bug as I was able to install the extension by going through all the steps again but using the root user to execute them.

**Comment by JLockerman** [comment]
@ebreijo I'm glad that worked!

I just finished trying to reproduce the build failure locally, but could not do so, likely because I was running as root. I'm not sure why a non-root build would fail in this manner; might be an issue with post-install not being able to read the install file correctly.

Anyway, that you for the bug report, even though we haven't yet found the originally issue, it led a [couple](https://github.com/timescale/timescaledb-toolkit/pull/189) of [fixes](https://github.com/timescale/timescaledb-toolkit/pull/190) to the install instructions; they should be a bit easier to follow now.

**Comment by CryptusChrist** [comment]
> Did you ever find an answer to this?

When I run as default user I get "Permission Denied (os error 13) ... then I run as root, and i get your same error message.  

Using Ubuntu 20.04

**Comment by zhiyong-ft** [comment]
https://github.com/timescale/timescaledb-toolkit/issues/188#issuecomment-1012516098
