### ISSUE TITLE
Look into using Apache Arrow/Parquet for function pipelines

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb-toolkit#321]
Before pipelines can be stabilized we need to decide which types they can work on: will they continue to be specialized to sets of `(TimestampTZ, DOUBLE PRECISION)` pairs, or will they work on more general layouts? If we want them to work with more general layouts, there are currently a few major issues that would need to be resolved:

1. Scope. Which kinds of types and layouts are supported.
2. Ergonomics. What does the interface look like for ingesting arbitrary types into a pipeline and, possibly more fraught, expanding a timevector of containing such types back into SQL? Right now the best for the latter would be to use an anonymous [record type](https://www.postgresql.org/docs/13/datatype-pseudo.html). Unfortunately as of the time of this comment extracting fields from such a record requires putting the function call in the `FROM` clause which is both syntactically undesirable, and has potential performance issues as it forces the functions entire contents to be materialized in a tuple table.
3. Storage. How would these types be stored in-memory and on-disk?

The effort for the defining and implementing the storage layouts could potentially be mitigated by using an existing layout scheme and library, such as Apache [Arrow](https://arrow.apache.org/) or [Parquet](https://parquet.apache.org/). We would need to investigate these a little to make sure they're suitable for our use case. In particular, Postgres typically uses the same layout for in-memory and on-disk which requires very fast deserialization, but there may be ways to mitigate this.

**Comment by smashra** [comment]
For fast deserialization Apache Arrow format seems perfect. Files on disk can be be memory mapped leading to effectively 0 copy cost. It's the same format for in-memory and on-disk obviously. 
Parquet will incur the cost of decompression when read into memory and the on-disk format of such files may not be standard as Apache Arrow.  But parquet files can be read into Apache Arrow  format for in-memory representation.
For real-time analytics Apache Arrow seems like it's the right candidate, in my view.
I can work on this and investigate more.

**Comment by JLockerman** [comment]
I think @WireBaron is also looking at opportunities to simplify the timevector implementation, so I'll point him at this

**Comment by smashra** [comment]
Cool!
@JLockerman what is the best place in the code to start looking into this.
This is just for my understanding.

**Comment by smashra** [comment]
Looks like : extension/src/time_series)/pipeline/ 
I'll first setup  my environment.

**Comment by WireBaron** [comment]
So it doesn't look like I'm going to have bandwidth to do any fundamental changes for our timevectors now, but I did want to jot down my quick findings here:
- in terms of layout, there doesn't seem to be a big advantage of using Arrow vs. columnar slices of data.  I couldn't find a way to get an entire Arrow array as a simple (addr,len) pair, so we can't just use it directly in our flat_serializable structures.
- It would provide nice handling for NULLs, which we currently still need to implement.  So that is something to consider.
- However, it does get between us and the underlying data, which can be annoying with Postgres data.  In particular, behavior for equality and cloning is not likely to be correct for all cases.  That being said, we probably would want to provide our own functions for such things anyways rather than relying on container behavior.
- Finally, while the `StructArray` that we'd likely want to use for the timevector is available, the rust Arrow implementation is still a work in progress.

All in all, it doesn't look like there's enough benefit to using Arrow to make it worthwhile at this point.
